---
abstract: 'Read individual characters from the keyboard using Win32::Console '
author:
  - 'Klaus Eichner <klaus03@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Win32-Readch
requires:
  Exporter: '0'
  Win32::Console: '0'
  Win32::IPC: '0'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/klaus03/Win32-Readch
  repository: https://github.com/klaus03/Win32-Readch.git
version: '0.05'
